# Generated by Django 4.2.2 on 2023-06-20 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Category')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Villains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Characters')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('content', models.TextField(blank=True, verbose_name='article text')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='photo')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Time of create')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Time of change')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publication')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='batman.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Known characters',
                'verbose_name_plural': 'Known characters',
                'ordering': ['time_create', 'title'],
            },
        ),
    ]
